[build]
  command = "mkdir -p public/reports public/assets/css public/assets/js && cp -rp reports/. public/reports/ && cp -rp assets/. public/assets/ && cp reports-index.json public/ && cp index.html public/ && echo 'Build OK'"
  publish = "public"
  functions = "netlify/functions"
